
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Markdown on Lint
        uses: bltavares/actions/mdlint@master

      -
        name: Dockerfile Lint
        uses: bltavares/actions/hadolint@master
  
